
spring:
  application:
    name: bugg
  datasource:
    url: jdbc:postgresql://localhost:5433/buggyshop
    username:
    password:
  flyway:
    locations: classpath:db/migration
    enable: true
    schemas: buggyshop
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework: ERROR

service:
  message: Hello, World